project_name: heimdall
before:
  hooks:
    - go mod download
builds:
  - id: heimdall
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
archives:
  - formats: ["tar.gz"]
checksum:
  name_template: "checksums.txt"
