language: go

sudo: false

env:
  global:
    - DATABASE_URL="postgres://postgres@localhost/travis_ci_test?sslmode=disable"

addons:
  postgresql: 9.4

go:
  - 1.4
  - tip

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: go test -v ./...

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_deploy: GOPATH=$HOME/gopath make release

deploy:
  provider: releases
  api_key:
    secure: jFZ4bY+/TGewdTr/ThOUb9OqCQs7ztlfEdTcy81l78X9US7pBxdyL7cyBAZCTRT2FAazQVzGGkAAQU3CxBvDblFahEZ3pzDLfo9cM5bNd1oWKKvVl7xleflsLbejSFVTFTJdHB1/j+vSPElmyZGLP9J83m4WQYhbebSj02cIbkw=
  file:
    - pkg/darwin_amd64_heimdall.tar.gz
    - pkg/linux_amd64_heimdall.tar.gz
  skip_cleanup: true
  on:
    repo: hectcastro/heimdall
    tags: true
