db:
  image: postgres:9.3
  ports:
    - "5432"

heimdall:
  build: .
  links:
    - db
  volumes:
    - pkg:/go/src/github.com/hectcastro/heimdall/pkg
  environment:
    - DATABASE_URL=postgres://postgres@db/postgres?sslmode=disable
